In [ ]:
import numpy as np
x = np.array([1, 2, 3,4,5,6,7,8,9])
even =(x%2==0)
odd=(x%2!=0)
y=x[even]
z=x[odd]
print("Even Numbers",y)
print("Odd Numbers",z)

Even Numbers [2 4 6 8]
Odd Numbers [1 3 5 7 9]


In [ ]:
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
a=np.diag(np.diag(matrix))
print(a)

[[1 0 0]
 [0 5 0]
 [0 0 9]]


**Convert a NumPy Array to 0 or 1 Array Based on Threshold Condition**

In [10]:
import numpy as np
x1 = np.array(range(16))
x1 = x1.reshape([4,4])
print("x1=",x1)
y1 = np.where(x1<=4, 1, 0)
print(y1)

x1= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1 1 1 1]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
import numpy as np
x1 = np.array(range(16))
x1 = x1.reshape([4,4])
print("x1=",x1)
x_mask = x1*3
y_mask = x1*-3
y1 = np.where(x1<=4, x_mask, y_mask)
print("y1=",y1)
y2 = np.where(np.logical_and(x1>=4, x1<=8), x_mask, y_mask)
print("y2=", y2)

x1= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
y1= [[  0   3   6   9]
 [ 12 -15 -18 -21]
 [-24 -27 -30 -33]
 [-36 -39 -42 -45]]
y2= [[  0  -3  -6  -9]
 [ 12  15  18  21]
 [ 24 -27 -30 -33]
 [-36 -39 -42 -45]]


**Understand NumPy Array Three Dots(…) or Ellipsis with Examples – NumPy Tutorial**

In [16]:
import numpy as np
x = np.arange(0,32).reshape(2,4, 4)
print("x =")
print(x)
print("x[:,:, 1] = ")
print(x[:,:, 1])
print("x[..., 1] = ")
print(x[..., 1])

x =
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
x[:,:, 1] = 
[[ 1  5  9 13]
 [17 21 25 29]]
x[..., 1] = 
[[ 1  5  9 13]
 [17 21 25 29]]


**Understand numpy.nonzero() with Examples – NumPy Tutorial**

In [17]:
import numpy as np
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
print(x)
y = np.nonzero(x)
print(len(y))
print(y)

[[3 0 0]
 [0 4 0]
 [5 6 0]]
2
(array([0, 1, 2, 2]), array([0, 1, 0, 1]))


In [18]:
import numpy as np
x = np.array([[1, 0, 3], [4, 0, 6], [7, 8, 9]])
print(x)
y = np.nonzero(x)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


**Convert NumPy Array Float to Int: A Step Guide – NumPy Tutorial**

In [28]:
import numpy as np
x = np.random.randn(2,3)
print(x, x.dtype)
print("\n")
y = x.astype(np.int16)
print(y, y.dtype)

[[-0.68739378 -0.82915761 -1.9164916 ]
 [ 0.89024897 -0.61486124 -1.25564322]] float64


[[ 0  0 -1]
 [ 0  0 -1]] int16


**Understand numpy.linspace() with Examples – NumPy Tutorial**

In [29]:
import numpy
startframe = numpy.linspace(start = 0, stop = 8, num=6)
print(startframe)

[0.  1.6 3.2 4.8 6.4 8. ]


In [30]:
import numpy
startframe = numpy.linspace(start = 0, stop = 8, num=6, endpoint=False)
print(startframe)

[0.         1.33333333 2.66666667 4.         5.33333333 6.66666667]


In [31]:
startframe = numpy.linspace(start = 0, stop = 0, num=6, endpoint=False)
print(startframe)

[0. 0. 0. 0. 0. 0.]


**Unit-normalize a NumPy Array: A Practice Guide – NumPy Tutorial**

In [32]:
import numpy as np
def unit(x, axis = 0):
    l2_norm = np.linalg.norm(x, keepdims=True, axis= axis) + 1e-12
    x_norm = x / l2_norm
    return x_norm

In [34]:
x = np.random.random((10))
y = unit(x)
print(x)
print(y)
x1 = np.sum(y*y)
print(x1)

[0.86719052 0.64230778 0.85130514 0.53249449 0.45110769 0.36559871
 0.9107579  0.29117781 0.16412428 0.36433075]
[0.45807191 0.33928317 0.44968085 0.28127702 0.23828646 0.19311846
 0.4810853  0.15380746 0.08669458 0.19244869]
0.9999999999989435


In [33]:
x = np.random.random((10))
y = unit(x)
print(x)
print(y)
x1 = np.sum(y*y)
print(x1)

[0.30886431 0.29093824 0.800035   0.92266363 0.11273366 0.77626041
 0.02037863 0.97053951 0.22018046 0.95525857]
[0.15088908 0.14213168 0.39084005 0.45074766 0.05507363 0.37922549
 0.00995555 0.4741364  0.10756448 0.46667123]
0.999999999999023


In [37]:
import numpy as np
x = np.random.random((10, 10))
y = unit(x, axis = 1)
print(x)
print(y)
x1 = np.sum(np.square(y), axis = 1)
print(x1)

[[0.22756265 0.75214659 0.22787555 0.48009621 0.84639073 0.60873261
  0.10874499 0.09852324 0.72462492 0.50282432]
 [0.69922514 0.61680331 0.36918009 0.17439931 0.81468961 0.18457588
  0.92822476 0.92052977 0.32023697 0.86768584]
 [0.72132035 0.34239487 0.87654112 0.02074257 0.12807278 0.17086948
  0.15561584 0.97928846 0.71756517 0.18609913]
 [0.62220653 0.98755343 0.22938999 0.99883995 0.23221522 0.07568171
  0.45193604 0.98353179 0.64694897 0.85623306]
 [0.67339728 0.13655772 0.18497905 0.6622837  0.44364869 0.91150796
  0.61847705 0.57874325 0.58991439 0.16329578]
 [0.84759171 0.15041558 0.76785197 0.77147812 0.30489784 0.3991161
  0.80406429 0.39287147 0.25035533 0.57819888]
 [0.28083435 0.39732908 0.55885231 0.4487922  0.96571888 0.84359488
  0.78292107 0.91304905 0.08012014 0.92388238]
 [0.12415598 0.88540911 0.13914474 0.33972906 0.5479893  0.32379239
  0.21418253 0.6161287  0.44850546 0.51231433]
 [0.64753228 0.43480108 0.19965503 0.75436593 0.79670896 0.25886794
  0.21202859 

Understand numpy.linalg.norm() with Examples: Calculate Matrix or Vector Norm – NumPy Tutorial

In [38]:
import numpy as np
x = np.random.random((2,3))
print(x)
y = np.linalg.norm(x, ord = np.inf)
print(y)

[[0.49203986 0.15095366 0.53904215]
 [0.15826327 0.65309534 0.4540774 ]]
1.2654360090178634


In [39]:
x2 = np.random.random((3,))
print(x2)
y = np.linalg.norm(x2, ord = np.inf)
print(y)

[0.0531414  0.23025992 0.35862845]
0.35862845387511955


In [40]:
import numpy as np
x = np.random.random((2,3))
print(x)
y = np.linalg.norm(x)
print(y)
y = np.linalg.norm(x, axis= 1)
print(y)

[[0.61016329 0.21684328 0.6891889 ]
 [0.79443584 0.32261412 0.16413033]]
1.287030897108298
[0.9456752  0.87301028]


Convert Boolean to 0 and 1 in NumPy – NumPy Tutorial


In [41]:
import numpy as np
mask = np.arange(1,16)
x = 10
t = mask<=x
print(t)
d = t.astype(int)
print(d)

[ True  True  True  True  True  True  True  True  True  True False False
 False False False]
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0]


In [42]:
# numpy.ndarray.byteswap()
import numpy as np
a = np.array([1, 256, 8755], dtype = np.int16)

print ('Our array is:')
print (a)
print ('\n')

print ('Representation of data in memory in hexadecimal form:')
print (map(hex,a))
print ('\n')
# byteswap() function swaps in place by passing True parameter

print ('Applying byteswap() function:')
print (a.byteswap(True))
print ('\n')

print ('In hexadecimal form:')
print (list (map(hex,a)) )
print ('\n')
# We can see the bytes being swapped


Our array is:
[   1  256 8755]


Representation of data in memory in hexadecimal form:


Applying byteswap() function:
[  256     1 13090]


In hexadecimal form:
['0x100', '0x1', '0x3322']




In [43]:
# Example 1
# convert list to ndarray
import numpy as np

x = [1,2,3]
a = np.asarray(x)
print (a)

[1 2 3]


In [46]:
# Example 2
# dtype is set
import numpy as np

x = [1,2,3]
a = np.asarray(x, dtype = float)
print (a)

[1. 2. 3.]


In [47]:
# Example 3
# ndarray from tuple
import numpy as np

x = (1,2,3)
a = np.asarray(x)
print (a)

[1 2 3]


In [48]:
# Example 4
# ndarray from list of tuples
import numpy as np

x = [(1,2,3),(4,5,)]
a = np.asarray(x)
print (a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [49]:
# Example 1
# create list object using range function
import numpy as np
list = range(5)
print (list)

range(0, 5)


In [50]:
# Example 2
# obtain iterator object from list
import numpy as np
list = range(5)
it = iter(list)

# use iterator to create ndarray
x = np.fromiter(it, dtype = float)
print (x)

[0. 1. 2. 3. 4.]
